import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Loader2, MapPinned, Radar, Search, ShieldCheck, Sparkles, XCircle, Zap } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { sweepApi, type SweepResult } from "@/lib/sweepApi";
import { useAuth } from "@/lib/auth";
import { useToast } from "@/hooks/use-toast";

type Stage = "all"|"fresh"|"available"|"unavailable";
type Customer = "all"|"new_opportunity"|"existing_customer"|"unknown";

export default function SweepCommand(){
  const {user}=useAuth(), qc=useQueryClient(), {toast}=useToast();
  const isAdmin=user?.role==="admin";
  const [city,setCity]=useState("Lexington"),[state,setState]=useState<"NC"|"SC">("NC"),[maxChecks,setMaxChecks]=useState(5000);
  const [address,setAddress]=useState(""),[radius,setRadius]=useState(500),[addressResult,setAddressResult]=useState<any>(null);
  const [selected,setSelected]=useState<string|null>(null),[stage,setStage]=useState<Stage>("all"),[customer,setCustomer]=useState<Customer>("all");
  const {data:list}=useQuery({queryKey:["/api/sweeps"],queryFn:sweepApi.list,refetchInterval:5000});
  const activeId=selected??list?.sweeps?.[0]?.id??null;
  const {data:job}=useQuery({queryKey:["/api/sweeps",activeId],queryFn:()=>sweepApi.get(activeId!),enabled:!!activeId,refetchInterval:(q)=>q.state.data?.status==="running"?2000:10000});
  const {data:results,isLoading}=useQuery({queryKey:["/api/sweeps",activeId,"results",stage,customer],queryFn:()=>sweepApi.results(activeId!,{stage:stage==="all"?undefined:stage,customer:customer==="all"?undefined:customer}),enabled:!!activeId,refetchInterval:job?.status==="running"?3000:false});
  const {data:knock}=useQuery({queryKey:["/api/sweeps",activeId,"knock"],queryFn:()=>sweepApi.knockList(activeId!),enabled:!!activeId,refetchInterval:job?.status==="running"?5000:false});
  const start=useMutation({mutationFn:()=>sweepApi.start({city:city.trim(),state,maxChecks}),onSuccess:(j)=>{setSelected(j.id);qc.invalidateQueries({queryKey:["/api/sweeps"]});toast({title:`${city} sweep queued`});},onError:(e:any)=>toast({title:e.message||"Could not start sweep",variant:"destructive"})});
  const startAddress=useMutation({mutationFn:()=>sweepApi.startAddress({query:address.trim(),radiusMeters:radius,maxChecks}),onSuccess:(j)=>{setSelected(j.id);qc.invalidateQueries({queryKey:["/api/sweeps"]});toast({title:"Address-area sweep queued"});},onError:(e:any)=>toast({title:e.message||"Could not start address sweep",variant:"destructive"})});
  const search=useMutation({mutationFn:()=>sweepApi.searchAddress(address,radius),onSuccess:setAddressResult,onError:(e:any)=>toast({title:e.message||"Address search failed",variant:"destructive"})});
  const exportCsv=async()=>{if(!activeId)return;const r=await apiRequest("GET",`/api/sweeps/${activeId}/knock-list.csv`);const blob=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`fresh-fiber-knock-list-${activeId}.csv`;a.click();URL.revokeObjectURL(a.href)};
  const pct=job?.queued?Math.round(job.checked/job.queued*100):0;
  return <div className="h-full min-h-0 overflow-y-auto bg-background pb-24">
    <div className="sticky top-0 z-20 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto max-w-7xl px-4 py-3 flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-emerald-500/15 text-emerald-500 flex items-center justify-center"><Radar className="h-5 w-5"/></div><div><h1 className="font-semibold tracking-tight">Fresh Fiber Sweep</h1><p className="text-xs text-muted-foreground">Address-level Kinetic launch intelligence</p></div>{job?.status==="running"&&<span className="ml-auto rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary"><span className="inline-block h-1.5 w-1.5 rounded-full bg-primary animate-pulse mr-1.5"/>{job.phase}</span>}</div></div>
    <main className="mx-auto max-w-7xl p-4 space-y-4">
      <section className="grid gap-3 lg:grid-cols-2">
        <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2 mb-3"><MapPinned className="h-4 w-4 text-primary"/><h2 className="text-sm font-semibold">Sweep a city</h2></div><div className="grid grid-cols-[1fr_76px] gap-2"><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City" className="h-11 rounded-xl border border-border bg-background px-3 text-sm"/><select value={state} onChange={e=>setState(e.target.value as any)} className="h-11 rounded-xl border border-border bg-background px-2 text-sm"><option>NC</option><option>SC</option></select></div><div className="mt-2 flex gap-2"><select value={maxChecks} onChange={e=>setMaxChecks(Number(e.target.value))} className="h-11 flex-1 rounded-xl border border-border bg-background px-3 text-sm"><option value={1000}>1,000 checks</option><option value={5000}>5,000 checks</option><option value={15000}>15,000 checks</option><option value={50000}>Full city, up to 50,000</option></select><button disabled={!isAdmin||start.isPending||!city.trim()} onClick={()=>start.mutate()} className="h-11 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{start.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:<span className="flex items-center gap-2"><Zap className="h-4 w-4"/>Start</span>}</button></div><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">OSM harvests first. Provider checks run in resumable 5,000-address batches with a hard spend cap.</p></div>
        <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2 mb-3"><Search className="h-4 w-4 text-primary"/><h2 className="text-sm font-semibold">Search an address area</h2></div><input value={address} onChange={e=>{setAddress(e.target.value);setAddressResult(null)}} placeholder="123 Main St, Lexington, NC" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm"/><div className="mt-2 flex gap-2"><select value={radius} onChange={e=>{setRadius(Number(e.target.value));setAddressResult(null)}} className="h-11 flex-1 rounded-xl border border-border bg-background px-3 text-sm"><option value={250}>250 m</option><option value={500}>500 m</option><option value={1000}>1 km</option><option value={2500}>2.5 km</option></select><button disabled={search.isPending||address.length<5} onClick={()=>search.mutate()} className="h-11 rounded-xl border border-border bg-secondary px-4 text-sm font-semibold disabled:opacity-50">{search.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:"Find"}</button></div>{addressResult&&<div className="mt-3 rounded-xl bg-emerald-500/10 p-3"><p className="text-xs text-emerald-600 dark:text-emerald-400">Found {addressResult.addresses.length.toLocaleString()} address points near {addressResult.match.displayName}</p><button disabled={!isAdmin||startAddress.isPending||!addressResult.addresses.length} onClick={()=>startAddress.mutate()} className="mt-2 h-10 w-full rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{startAddress.isPending?<Loader2 className="mx-auto h-4 w-4 animate-spin"/>:"Check this address area"}</button></div>}</div>
      </section>
      {job&&<><section className="rounded-2xl border border-border bg-card overflow-hidden"><div className="p-4 flex items-start gap-3"><div className="min-w-0 flex-1"><div className="font-semibold truncate">{job.city?`${job.city}, ${job.state}`:job.query}</div><div className="text-xs text-muted-foreground">{job.source??"Preparing inventory"} · started {new Date(job.startedAt).toLocaleString()}</div></div>{job.status==="error"&&<span className="text-xs text-red-500">{job.error}</span>}{job.status==="running"&&isAdmin&&<button onClick={()=>sweepApi.cancel(job.id).then(()=>qc.invalidateQueries())} className="h-9 px-3 rounded-lg border border-border text-xs"><XCircle className="inline h-3.5 w-3.5 mr-1"/>Cancel</button>}</div><div className="grid grid-cols-2 sm:grid-cols-5 border-t border-border divide-x divide-border"><Metric label="Harvested" value={job.harvested}/><Metric label="Checked" value={job.checked}/><Metric label="Fresh" value={job.freshFound} hot/><Metric label="New opportunities" value={job.opportunitiesFound} hot/><Metric label="Failures" value={job.failed}/></div>{job.status==="running"&&<div className="h-1.5 bg-secondary"><div className="h-full bg-primary transition-all" style={{width:`${pct}%`}}/></div>}</section>
      <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><SweepMap rows={results?.results??[]}/><div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">First-mover knock list</h2><p className="text-xs text-muted-foreground">Fresh + provider-indicated non-customer</p></div><button disabled={!knock?.count} onClick={exportCsv} className="h-10 rounded-xl border border-border px-3 text-xs font-semibold disabled:opacity-40"><Download className="inline h-4 w-4 mr-1"/>CSV</button></div><div className="mt-4 text-4xl font-bold text-emerald-500 tabular-nums">{knock?.count??0}</div><div className="mt-3 space-y-2">{knock?.rows?.slice(0,5).map((r:any)=><a key={r.address} href={r.map_url} target="_blank" rel="noreferrer" className="block rounded-xl bg-secondary/50 p-3"><div className="flex justify-between gap-2"><span className="text-sm font-medium truncate">{r.address}</span><span className="text-xs font-bold text-emerald-500">{r.opportunity_score}</span></div><div className="mt-1 text-[11px] text-muted-foreground">Cluster {r.cluster_density} · {r.fresh_confidence.replaceAll("_"," ")}</div></a>)}</div></div></section>
      <section className="rounded-2xl border border-border bg-card"><div className="p-3 flex gap-2 overflow-x-auto"><Filter label="All" active={stage==="all"&&customer==="all"} onClick={()=>{setStage("all");setCustomer("all")}}/><Filter label="Fresh" active={stage==="fresh"} onClick={()=>setStage("fresh")}/><Filter label="Available" active={stage==="available"} onClick={()=>setStage("available")}/><Filter label="Unavailable" active={stage==="unavailable"} onClick={()=>setStage("unavailable")}/><Filter label="New opportunity" active={customer==="new_opportunity"} onClick={()=>setCustomer("new_opportunity")}/><Filter label="Existing" active={customer==="existing_customer"} onClick={()=>setCustomer("existing_customer")}/></div><div className="divide-y divide-border">{isLoading?<div className="p-8 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin"/></div>:results?.results?.slice(0,100).map(r=><ResultRow key={r.id} row={r}/>)}{!isLoading&&!results?.results.length&&<div className="p-8 text-center text-sm text-muted-foreground">No results in this view yet.</div>}</div></section></>}
      {!!list?.sweeps?.length&&<section><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Recent sweeps</h2><div className="flex gap-2 overflow-x-auto pb-2">{list.sweeps.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} className={`min-w-48 rounded-xl border p-3 text-left ${activeId===s.id?"border-primary bg-primary/5":"border-border bg-card"}`}><div className="text-sm font-semibold truncate">{s.city?`${s.city}, ${s.state}`:s.query}</div><div className="text-[11px] text-muted-foreground">{s.status} · {s.checked.toLocaleString()} checked</div></button>)}</div></section>}
    </main>
  </div>
}
function Metric({label,value,hot}:{label:string;value:number;hot?:boolean}){return <div className="p-3"><div className={`text-xl font-bold tabular-nums ${hot?"text-emerald-500":""}`}>{value.toLocaleString()}</div><div className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</div></div>}
function Filter({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`h-9 whitespace-nowrap rounded-full px-3 text-xs font-semibold ${active?"bg-primary text-primary-foreground":"bg-secondary text-muted-foreground"}`}>{label}</button>}
function ResultRow({row:r}:{row:SweepResult}){const fresh=r.transitionStatus==="freshly_available";const tone=fresh&&r.customerSegment==="new_opportunity"?"bg-emerald-500":r.fiberAvailable?r.customerSegment==="existing_customer"?"bg-violet-500":"bg-blue-500":"bg-slate-500";return <div className="p-3 flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${tone}`}/><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{r.address}</div><div className="text-[11px] text-muted-foreground">{r.customerSegment.replaceAll("_"," ")} · {r.transitionStatus??"pending"}</div></div>{r.crossVerified?<span title="Cross-verified"><ShieldCheck className="h-4 w-4 text-emerald-500"/></span>:fresh?<span title="Provisional"><Sparkles className="h-4 w-4 text-amber-500"/></span>:null}<div className="text-right text-xs tabular-nums">{r.maxDownloadMbps?`${r.maxDownloadMbps} Mbps`:"—"}</div></div>}
function SweepMap({rows}:{rows:SweepResult[]}){const el=useRef<HTMLDivElement>(null),map=useRef<any>(null);const points=useMemo(()=>rows.filter(r=>r.lat!=null&&r.lng!=null),[rows]);useEffect(()=>{let dead=false;(async()=>{if(!el.current||map.current||!(window as any).mapboxgl)return;const d=await(await apiRequest("GET","/api/config/map")).json();if(dead)return;(window as any).mapboxgl.accessToken=d.token;const m=new (window as any).mapboxgl.Map({container:el.current,style:"mapbox://styles/mapbox/streets-v12",center:[-80.25,35.82],zoom:10});map.current=m;m.on("load",()=>{m.addSource("sweep",{type:"geojson",data:{type:"FeatureCollection",features:[]}});m.addLayer({id:"sweep-points",type:"circle",source:"sweep",paint:{"circle-radius":["case",["==",["get","freshOpportunity"],true],8,6],"circle-color":["case",["==",["get","freshOpportunity"],true],"#16a34a",["==",["get","customer"],"existing_customer"],"#8b5cf6",["==",["get","available"],true],"#3b82f6","#64748b"],"circle-stroke-width":2,"circle-stroke-color":"#ffffff"}})});})();return()=>{dead=true;map.current?.remove();map.current=null}},[]);useEffect(()=>{const m=map.current;if(!m?.getSource("sweep"))return;const data={type:"FeatureCollection",features:points.map(r=>({type:"Feature",geometry:{type:"Point",coordinates:[r.lng,r.lat]},properties:{available:r.fiberAvailable,customer:r.customerSegment,freshOpportunity:r.transitionStatus==="freshly_available"&&r.customerSegment==="new_opportunity"}}))};m.getSource("sweep").setData(data);if(points.length){const b=new (window as any).mapboxgl.LngLatBounds();points.forEach(r=>b.extend([r.lng,r.lat]));m.fitBounds(b,{padding:40,maxZoom:15,duration:500})}},[points]);return <div className="min-h-80 overflow-hidden rounded-2xl border border-border bg-secondary"><div ref={el} className="h-80 w-full"/></div>}
