/**
 * calling/scriptEngine.ts — personalized, compliance-safe call-script generation
 * for the Kinetic Fiber (Windstream) door-to-door cold-calling unit.
 *
 * Design guarantees:
 *  - Deterministic rules TEMPLATE first: a complete script is always built
 *    server-side from lead context (never client-supplied data).
 *  - Optional LLM ENHANCEMENT: when LLM_ENDPOINT/OPENAI_API_KEY is configured the
 *    template + context are rephrased by the model under a 2s budget. ANY
 *    failure, timeout, malformed output, or prohibited content in the model
 *    output falls back to the rules template verbatim. There is no pre-existing
 *    AI/agent gateway in this codebase (verified by grep), so the integration
 *    uses the OpenAI-compatible chat-completions shape over fetch.
 *  - The compliance footer is a fixed constant, appended verbatim to every
 *    script and never passed to or generated by the model.
 *  - Scripts are representative GUIDANCE only. Eligibility gating (DNC,
 *    attempts, windows) stays in the compliance engine; a script is never
 *    authorization to dial.
 *  - Output must never promise "free", invent urgency, or disparage named
 *    competitors — enforced on template AND model output.
 */
import { rawDb } from "../db";

export const SCRIPT_ENGINE_VERSION = "script-engine.v1";
export const SCRIPT_CACHE_TTL_MS = 6 * 60 * 60 * 1_000; // 6h
const LLM_TIMEOUT_MS = 2_000;
const CACHE_MAX_ENTRIES = 500;

/** Fixed compliance footer — ALWAYS appended verbatim, never model-generated. */
export const COMPLIANCE_FOOTER = [
  "---- COMPLIANCE NOTES (REP GUIDANCE — NEVER READ ALOUD UNLESS REQUIRED) ----",
  "1. Opening disclosure (REQUIRED at the start of every call): state your name, the company you are calling on behalf of, that this is a sales call, and that the purpose of the call is to offer Kinetic Fiber internet service.",
  "2. Do-Not-Call check: if this household is on any Do-Not-Call list, has an active opt-out, or asks not to be called, DO NOT read this script. End the call politely and record the DO_NOT_CALL disposition immediately.",
  "3. Never claim that service or equipment costs nothing, never invent deadlines or urgency, and never criticize or disparage a competitor by name.",
  "4. This script is guidance only. Call eligibility is enforced separately by the compliance engine; a generated script is never authorization to dial.",
].join("\n");

/** Patterns that may never appear in generated script output. */
const PROHIBITED_PATTERNS: RegExp[] = [
  /\bfree\b/i,
  /\b(act now|hurry|hurry up|limited[- ]time|expires? (today|tonight|soon)|today only|don'?t wait|last chance|offer ends|while supplies last)\b/i,
  /\b(spectrum|comcast|xfinity|at&t|verizon|frontier|centurylink|hughesnet|t-mobile|dish network|directv)\b/i,
];

export const PROHIBITED_CONTENT_DESCRIPTION =
  "No no-cost claims, no fabricated urgency or deadlines, no named-competitor disparagement.";

export function containsProhibitedContent(text: string): boolean {
  return PROHIBITED_PATTERNS.some((pattern) => pattern.test(text));
}

export type FiberCategory = "fresh" | "coming_soon" | "tenured" | "unknown";

export type ScriptLeadRow = {
  id: number;
  address: string;
  city: string;
  state: string;
  zip: string;
  fiberStatus?: string | null;
  leadTag?: string | null;
  isTenured?: number | boolean | null;
  freshConfirmedAt?: string | null;
  sourceScanTargetId?: number | null;
};

export type ScriptContext = {
  tenantId: number;
  leadId: number;
  address: string;
  city: string;
  state: string;
  zip: string;
  street: string;
  fiberCategory: FiberCategory;
  freshCityCount21d: number;
  onComingSoonWatchlist: boolean;
  nearestFreshStreet: string | null;
  repName: string;
  companyName: string;
};

export type ObjectionHandlers = {
  price: string;
  currentProvider: string;
  renter: string;
  worksFine: string;
};

export type ScriptSections = {
  opener: string;
  neighborhoodHook: string;
  valueProposition: string;
  objectionHandlers: ObjectionHandlers;
  close: string;
};

export type GeneratedScript = {
  version: string;
  model: "rules" | "llm";
  generatedAt: string;
  cached: boolean;
  context: {
    leadId: number;
    city: string;
    state: string;
    fiberCategory: FiberCategory;
    freshCityCount21d: number;
    onComingSoonWatchlist: boolean;
    nearestFreshStreet: string | null;
  };
  sections: ScriptSections & { complianceFooter: string };
  script: string;
};

/** "100 Manual Call St" -> "Manual Call St" (best-effort street-name strip). */
function streetOf(address: string): string {
  const stripped = String(address ?? "").replace(/^\s*\d+[A-Za-z]?(?:-\d+)?\s+/, "").trim();
  return stripped || String(address ?? "").trim();
}

function isOnComingSoonWatchlist(tenantId: number, lead: ScriptLeadRow): boolean {
  if (String(lead.leadTag ?? "") === "coming_soon") return true;
  if (lead.sourceScanTargetId != null) {
    try {
      if (rawDb.prepare(`SELECT 1 FROM coming_soon_watchlist
        WHERE tenant_id=? AND scan_target_id=? AND status='active' LIMIT 1`)
        .get(tenantId, lead.sourceScanTargetId)) return true;
    } catch { /* watchlist table absent in this schema — fall through */ }
  }
  try {
    if (rawDb.prepare(`SELECT 1 FROM coming_soon_watch
      WHERE tenant_id=? AND lower(address)=lower(?) AND lower(city)=lower(?) AND status='watching' LIMIT 1`)
      .get(tenantId, lead.address, lead.city)) return true;
  } catch { /* coming_soon_watch table absent in this schema — fall through */ }
  return false;
}

/**
 * All personalization context is pulled server-side from tenant-scoped rows.
 * The 21-day momentum window uses datetime(created_at) normalization (the
 * leads table holds both 'YYYY-MM-DD HH:MM:SS' and ISO formats).
 */
export function buildScriptContext(input: {
  tenantId: number;
  lead: ScriptLeadRow;
  repName: string;
  companyName: string;
}): ScriptContext {
  const { tenantId, lead } = input;
  const onComingSoonWatchlist = isOnComingSoonWatchlist(tenantId, lead);
  const fiberStatus = String(lead.fiberStatus ?? "").toLowerCase();
  const fresh = String(lead.leadTag ?? "") === "fresh_fiber_confirmed" || Boolean(lead.freshConfirmedAt);
  const comingSoon = !fresh && (String(lead.leadTag ?? "") === "coming_soon"
    || fiberStatus === "coming_soon" || onComingSoonWatchlist);
  const tenured = !fresh && !comingSoon
    && (Number(lead.isTenured) === 1 || ["available", "tenured", "live"].includes(fiberStatus));
  const fiberCategory: FiberCategory = fresh ? "fresh" : comingSoon ? "coming_soon" : tenured ? "tenured" : "unknown";

  // Window keys on the CONFIRMATION time (falling back to row creation) so the
  // spoken "confirmed in the last three weeks" claim matches the window.
  const momentum = rawDb.prepare(`SELECT COUNT(*) AS n FROM leads
    WHERE tenant_id=? AND lead_tag='fresh_fiber_confirmed' AND lower(city)=lower(?)
      AND datetime(coalesce(fresh_confirmed_at,created_at)) >= datetime('now','-21 days')`)
    .get(tenantId, lead.city) as { n: number };
  // Most-RECENTLY confirmed other fresh lead in the city — no proximity claim.
  const nearest = rawDb.prepare(`SELECT address FROM leads
    WHERE tenant_id=? AND lead_tag='fresh_fiber_confirmed' AND lower(city)=lower(?) AND id<>?
    ORDER BY datetime(coalesce(fresh_confirmed_at,created_at)) DESC LIMIT 1`)
    .get(tenantId, lead.city, lead.id) as { address: string } | undefined;

  return {
    tenantId,
    leadId: lead.id,
    address: lead.address,
    city: lead.city,
    state: lead.state,
    zip: lead.zip,
    street: streetOf(lead.address),
    fiberCategory,
    freshCityCount21d: Number(momentum?.n ?? 0),
    onComingSoonWatchlist,
    nearestFreshStreet: nearest ? streetOf(nearest.address) : null,
    repName: input.repName,
    companyName: input.companyName,
  };
}

function neighborhoodHook(context: ScriptContext): string {
  const { city, street, fiberCategory, freshCityCount21d, onComingSoonWatchlist, nearestFreshStreet } = context;
  switch (fiberCategory) {
    case "fresh": {
      const momentum = freshCityCount21d > 1
        ? ` ${freshCityCount21d} homes in ${city} have been confirmed for brand-new fiber in the last three weeks${nearestFreshStreet ? `, including homes on ${nearestFreshStreet}` : ""}.`
        : "";
      return `The reason for my call: Kinetic Fiber just came to ${street} here in ${city}.${momentum} Your address was just confirmed for the new fiber build, so we're calling neighbors to answer questions and offer a quick availability check.`;
    }
    case "coming_soon":
      return `The reason for my call: Kinetic Fiber construction is underway in ${city}, and ${street} is in the coming-soon build area.${onComingSoonWatchlist ? " Your address is on our watch list, which means we'll know the moment service can be installed." : ""} I'm calling so you're first to know when your address can order.`;
    case "tenured":
      return `The reason for my call: Kinetic Fiber has been available in ${city} for a while now, and we've found a lot of households on ${street} haven't taken a fresh look at what fiber offers compared with what they've had for years.`;
    default:
      return `The reason for my call: we're expanding Kinetic Fiber service across ${city}, and I wanted to check what your address on ${street} currently qualifies for.`;
  }
}

/** Deterministic rules template — always works, always compliant. */
export function buildTemplateSections(context: ScriptContext): ScriptSections {
  return {
    opener: `Hi, my name is ${context.repName}, and I'm calling on behalf of ${context.companyName}, an authorized seller of Kinetic Fiber internet from Windstream. This is a sales call about fiber internet service at ${context.address} in ${context.city}. Did I catch you at an okay time for about one minute?`,
    neighborhoodHook: neighborhoodHook(context),
    valueProposition: `Kinetic Fiber runs on a fiber-optic line rather than older cable or copper, which means symmetrical upload and download speeds and a connection that holds up when everyone is home. For working from home, that means video calls that don't freeze; for streaming, no buffering at dinner time; and for gaming, low, consistent latency. It's a straightforward reliability upgrade, and I can check exactly what your address qualifies for.`,
    objectionHandlers: {
      price: `That's a completely fair question. Pricing depends on the speed tier you choose, and many households find fiber costs about the same as what they already pay for slower service. With your permission, I can look up the exact plans and current pricing for your address — no obligation — so you can compare real numbers. Would that be useful?`,
      currentProvider: `That makes sense — most people I speak with already have internet and it's a hassle to think about changing. The difference with fiber is consistency: the speeds you're promised hold up in the evening, and uploads match downloads, which matters for video calls and cloud backups. There's no pressure to switch today; would it help if I simply checked what your address qualifies for so you have the option?`,
      renter: `Good question, and you're not alone — plenty of renters get fiber. Service is set up in your name, just like your current internet, and installation at an already-serviceable address is usually simple. If your landlord ever has questions, we can leave information for them. Can I check what your address qualifies for while I have you?`,
      worksFine: `Glad to hear it's working — that's honestly the best starting point. Most folks I talk to felt the same until the whole household was online at once or a big upload crawled. Fiber is really about headroom: everything keeps working the same at 8 p.m. as it does at 8 a.m. Would you be open to a quick availability check so you know your options before you ever need them?`,
    },
    close: `Here's all I'd suggest: let me run a quick availability and speed check for ${context.address} right now. It takes about a minute, there's no obligation, and you'll know exactly what your address can get. If it makes sense, we can talk about next steps at whatever pace works for you. Can I run that check for you?`,
  };
}

export function assembleScript(sections: ScriptSections): string {
  return [
    "[OPENER — read verbatim]",
    sections.opener,
    "",
    "[WHY THIS HOME — neighborhood hook]",
    sections.neighborhoodHook,
    "",
    "[VALUE — fiber vs. what they have today]",
    sections.valueProposition,
    "",
    "[OBJECTION HANDLERS]",
    `If they say it's too expensive: ${sections.objectionHandlers.price}`,
    `If they're happy with their current provider: ${sections.objectionHandlers.currentProvider}`,
    `If they rent the home: ${sections.objectionHandlers.renter}`,
    `If they say what they have works fine: ${sections.objectionHandlers.worksFine}`,
    "",
    "[CLOSE — soft ask]",
    sections.close,
    "",
    COMPLIANCE_FOOTER,
  ].join("\n");
}

// ── LLM enhancement (optional, fail-safe) ────────────────────────────────────

type LlmTransport = (request: {
  endpoint: string;
  apiKey: string | null;
  model: string;
  messages: Array<{ role: string; content: string }>;
  timeoutMs: number;
}) => Promise<string>;

async function defaultLlmTransport(request: Parameters<LlmTransport>[0]): Promise<string> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), request.timeoutMs);
  try {
    const response = await fetch(request.endpoint, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        ...(request.apiKey ? { authorization: `Bearer ${request.apiKey}` } : {}),
      },
      body: JSON.stringify({
        model: request.model,
        messages: request.messages,
        temperature: 0.4,
        max_tokens: 1_500,
        response_format: { type: "json_object" },
      }),
      signal: controller.signal,
    });
    if (!response.ok) throw new Error(`LLM endpoint returned ${response.status}`);
    const data = await response.json() as any;
    const content = data?.choices?.[0]?.message?.content;
    if (typeof content !== "string" || !content.trim()) throw new Error("LLM returned no content");
    return content;
  } finally {
    clearTimeout(timer);
  }
}

let llmTransport: LlmTransport = defaultLlmTransport;

/** Test hook: swap the LLM transport (null restores the default fetch transport). */
export function __setScriptEngineLlmTransportForTests(transport: LlmTransport | null): void {
  llmTransport = transport ?? defaultLlmTransport;
}

function llmConfig(): { endpoint: string; apiKey: string | null; model: string } | null {
  const endpoint = process.env.LLM_ENDPOINT?.trim()
    || (process.env.OPENAI_API_KEY?.trim() ? "https://api.openai.com/v1/chat/completions" : "");
  if (!endpoint) return null;
  return {
    endpoint,
    apiKey: process.env.LLM_API_KEY?.trim() || process.env.OPENAI_API_KEY?.trim() || null,
    model: process.env.LLM_MODEL?.trim() || "gpt-4o-mini",
  };
}

function validString(value: unknown, maxLength: number): value is string {
  return typeof value === "string" && value.trim().length >= 20 && value.length <= maxLength;
}

/**
 * Returns model-rephrased sections, or null on ANY failure — caller falls back
 * to the rules template verbatim. The compliance footer is never sent to or
 * accepted from the model.
 */
async function enhanceWithLlm(sections: ScriptSections, context: ScriptContext): Promise<ScriptSections | null> {
  const config = llmConfig();
  if (!config) return null;
  try {
    const content = await llmTransport({
      ...config,
      timeoutMs: LLM_TIMEOUT_MS,
      messages: [
        {
          role: "system",
          content: [
            "You rephrase outbound sales-call script sections for Kinetic Fiber (Windstream) internet so they sound natural and conversational.",
            "Hard rules: keep every fact and placeholder value unchanged; never claim anything is free; never invent urgency, scarcity, or deadlines; never name or disparage a competitor; keep the opening sales-call disclosure intact.",
            `Respond with strict JSON only: {"opener": string, "neighborhoodHook": string, "valueProposition": string, "objectionHandlers": {"price": string, "currentProvider": string, "renter": string, "worksFine": string}, "close": string}.`,
          ].join(" "),
        },
        {
          role: "user",
          content: JSON.stringify({
            leadContext: {
              city: context.city, state: context.state, street: context.street,
              fiberCategory: context.fiberCategory, freshCityCount21d: context.freshCityCount21d,
              onComingSoonWatchlist: context.onComingSoonWatchlist,
              nearestFreshStreet: context.nearestFreshStreet,
            },
            sections,
          }),
        },
      ],
    });
    const parsed = JSON.parse(content) as any;
    const handlers = parsed?.objectionHandlers ?? {};
    const candidate: ScriptSections = {
      opener: parsed?.opener,
      neighborhoodHook: parsed?.neighborhoodHook,
      valueProposition: parsed?.valueProposition,
      objectionHandlers: {
        price: handlers?.price,
        currentProvider: handlers?.currentProvider,
        renter: handlers?.renter,
        worksFine: handlers?.worksFine,
      },
      close: parsed?.close,
    };
    const flat = [
      candidate.opener, candidate.neighborhoodHook, candidate.valueProposition, candidate.close,
      candidate.objectionHandlers.price, candidate.objectionHandlers.currentProvider,
      candidate.objectionHandlers.renter, candidate.objectionHandlers.worksFine,
    ];
    if (!flat.every((value) => validString(value, 2_000))) return null;
    if (flat.some((value) => containsProhibitedContent(value as string))) return null;
    // Mandatory opening disclosure must survive rephrasing: the opener is read
    // verbatim, so the sales-call disclosure and the rep's own name are
    // non-negotiable. Missing either → discard the model output entirely.
    if (!/sales call/i.test(candidate.opener)) return null;
    if (!candidate.opener.toLowerCase().includes(context.repName.trim().toLowerCase())) return null;
    return candidate;
  } catch {
    return null;
  }
}

// ── Cache (per tenant+lead+version, 6h TTL) ──────────────────────────────────

type CacheEntry = { expiresAt: number; payload: Omit<GeneratedScript, "cached"> };
const scriptCache = new Map<string, CacheEntry>();

// The opener is a read-verbatim verbal disclosure containing the CALLING
// user's name — the cache key must include the requesting user or a second
// rep would read the first rep's name aloud from a stale cache entry.
function cacheKey(tenantId: number, userId: number, leadId: number): string {
  return `${tenantId}:${userId}:${leadId}:${SCRIPT_ENGINE_VERSION}`;
}

/** Test hook: drop all cached scripts. */
export function __clearScriptCacheForTests(): void {
  scriptCache.clear();
}

function cacheGet(tenantId: number, userId: number, leadId: number): CacheEntry | null {
  const key = cacheKey(tenantId, userId, leadId);
  const entry = scriptCache.get(key);
  if (!entry) return null;
  if (entry.expiresAt <= Date.now()) {
    scriptCache.delete(key);
    return null;
  }
  return entry;
}

function cacheSet(tenantId: number, userId: number, leadId: number, payload: Omit<GeneratedScript, "cached">): void {
  const now = Date.now();
  for (const [key, entry] of scriptCache) {
    if (entry.expiresAt <= now) scriptCache.delete(key);
  }
  if (scriptCache.size >= CACHE_MAX_ENTRIES) {
    const oldest = scriptCache.keys().next().value;
    if (oldest !== undefined) scriptCache.delete(oldest);
  }
  scriptCache.set(cacheKey(tenantId, userId, leadId), { expiresAt: now + SCRIPT_CACHE_TTL_MS, payload });
}

// ── Public entry points ──────────────────────────────────────────────────────

export async function generateScriptForLead(input: {
  tenantId: number;
  /** Requesting user — part of the cache key because the opener names them. */
  userId: number;
  lead: ScriptLeadRow;
  repName: string;
  companyName: string;
}): Promise<GeneratedScript> {
  const cached = cacheGet(input.tenantId, input.userId, input.lead.id);
  if (cached) return { ...cached.payload, cached: true };

  const context = buildScriptContext(input);
  const rulesSections = buildTemplateSections(context);
  const enhanced = await enhanceWithLlm(rulesSections, context);
  const sections = enhanced ?? rulesSections;
  const payload: Omit<GeneratedScript, "cached"> = {
    version: SCRIPT_ENGINE_VERSION,
    model: enhanced ? "llm" : "rules",
    generatedAt: new Date().toISOString(),
    context: {
      leadId: context.leadId,
      city: context.city,
      state: context.state,
      fiberCategory: context.fiberCategory,
      freshCityCount21d: context.freshCityCount21d,
      onComingSoonWatchlist: context.onComingSoonWatchlist,
      nearestFreshStreet: context.nearestFreshStreet,
    },
    sections: { ...sections, complianceFooter: COMPLIANCE_FOOTER },
    script: assembleScript(sections),
  };
  cacheSet(input.tenantId, input.userId, input.lead.id, payload);
  return { ...payload, cached: false };
}

/** Base template with placeholders — for admin preview of every section/variant. */
export function baseTemplatePreview(): {
  version: string;
  cacheTtlSeconds: number;
  sections: ScriptSections;
  hookVariants: Record<FiberCategory, string>;
  complianceFooter: string;
  prohibitedContent: string;
  llmEnhancement: { configured: boolean; timeoutMs: number; fallback: string };
} {
  const baseContext: ScriptContext = {
    tenantId: 0,
    leadId: 0,
    address: "[LEAD ADDRESS]",
    city: "[CITY]",
    state: "[ST]",
    zip: "[ZIP]",
    street: "[STREET OR NEIGHBORHOOD]",
    fiberCategory: "fresh",
    freshCityCount21d: 7,
    onComingSoonWatchlist: true,
    nearestFreshStreet: "[NEARBY FRESH STREET]",
    repName: "[REP NAME]",
    companyName: "[COMPANY]",
  };
  const hookVariants: Record<FiberCategory, string> = {
    fresh: neighborhoodHook({ ...baseContext, fiberCategory: "fresh" }),
    coming_soon: neighborhoodHook({ ...baseContext, fiberCategory: "coming_soon" }),
    tenured: neighborhoodHook({ ...baseContext, fiberCategory: "tenured" }),
    unknown: neighborhoodHook({ ...baseContext, fiberCategory: "unknown" }),
  };
  return {
    version: SCRIPT_ENGINE_VERSION,
    cacheTtlSeconds: SCRIPT_CACHE_TTL_MS / 1_000,
    sections: buildTemplateSections(baseContext),
    hookVariants,
    complianceFooter: COMPLIANCE_FOOTER,
    prohibitedContent: PROHIBITED_CONTENT_DESCRIPTION,
    llmEnhancement: {
      configured: Boolean(llmConfig()),
      timeoutMs: LLM_TIMEOUT_MS,
      fallback: "On any model error, timeout, malformed output, or prohibited content, the rules template is returned verbatim.",
    },
  };
}
