import crypto from "node:crypto";
import type { Express,NextFunction,Request,Response } from "express";
import { z } from "zod";
import type { Capability } from "@shared/capabilities";
import { rawDb } from "./db";
import { getDefaultTenantId,storage } from "./storage";
import { enrichCallingLead } from "./calling/providers";
import { getKineticProviderAdapter,kineticAddressSearchSchema,normalizeConfiguredKineticResponse } from "./kineticProviderAdapter";
import { clearKineticData,ensureKineticScannerSchema,scannerState,stats,upsertKineticAddress } from "./kineticScannerStore";
import { pauseKineticScan,resumeKineticScan,resumeKineticWorkersAfterRestart,startKineticRecheck,startKineticScan,stopKineticWorker } from "./kineticScannerWorkers";

type Middleware=(req:Request,res:Response,next:NextFunction)=>unknown;
interface Deps{requireCapability:(capability:Capability)=>Middleware;requireScanningAllowed:Middleware;scanAdmission:Middleware}
const KINETIC_STATES=["AL","AR","FL","GA","IA","KY","MN","MS","MO","NE","NM","NY","NC","OH","OK","PA","SC","TX"] as const;
const rangeSchema=z.object({startSequentialId:z.number().int().nonnegative(),endSequentialId:z.number().int().nonnegative()}).strict();
const listSchema=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(50),search:z.string().trim().max(160).optional(),state:z.enum(KINETIC_STATES).optional(),discoveryState:z.enum(["BASELINE_FIBER","NON_FIBER","CANDIDATE_FRESH","VERIFIED_FRESH","REGRESSED","SOURCE_ERROR"]).optional(),liveOnly:z.enum(["true","false"]).optional(),comingSoonOnly:z.enum(["true","false"]).optional(),copperUpgradeCandidateOnly:z.enum(["true","false"]).optional()});
const idSchema=z.coerce.number().int().positive();
function tenant(req:Request):number|null{const n=Number((req as any).user?.tenantId??getDefaultTenantId());return Number.isInteger(n)&&n>0?n:null;}
function actor(req:Request):number|null{const n=Number((req as any).user?.id);return Number.isInteger(n)&&n>0?n:null;}
function requireTenant(req:Request,res:Response):number|null{const id=tenant(req);if(!id)res.status(403).json({error:"Organization required"});return id;}
function parseRaw(value:string):unknown{try{return JSON.parse(value);}catch{return null;}}
function addressRow(tenantId:number,id:number):any{return rawDb.prepare(`SELECT a.id,a.kinetic_address_id AS kineticAddressId,a.sequential_id AS sequentialId,a.address,a.city,a.state,a.zip,a.latitude,a.longitude,
  exchange_id AS exchangeId,technology_type AS technologyType,maximum_qualification AS maximumQualification,estimated_completion_date AS estimatedCompletionDate,
  is_live AS isLive,is_coming_soon AS isComingSoon,is_copper_upgrade_candidate AS isCopperUpgradeCandidate,lead_id AS leadId,
  contact_enrichment_status AS contactEnrichmentStatus,first_seen_at AS firstSeenAt,last_checked_at AS lastChecked,last_status_change_at AS lastStatusChange,
  s.canonical_state AS canonicalState,s.discovery_state AS discoveryState,s.confirmation_count AS confirmationCount,s.last_non_fiber_at AS lastNonFiberAt,s.candidate_first_seen_at AS candidateFirstSeenAt,s.verified_at AS verifiedAt,s.model_version AS modelVersion
  FROM kinetic_addresses a LEFT JOIN kinetic_address_state s ON s.address_id=a.id WHERE a.tenant_id=? AND a.id=?`).get(tenantId,id);}
function csvCell(value:unknown):string{return `"${String(value??"").replaceAll('"','""')}"`;}

export function registerKineticScannerRoutes(app:Express,deps:Deps):void{
  ensureKineticScannerSchema();resumeKineticWorkersAfterRestart();
  const read=deps.requireCapability("scan.manage"),manage=deps.requireCapability("scan.manage");
  app.get("/api/kinetic-scanner/ping",read,async(req,res)=>{const result=await getKineticProviderAdapter().healthCheck(),tid=tenant(req);if(tid)rawDb.prepare(`INSERT INTO kinetic_provider_health (tenant_id,provider_name,ok,latency_ms,message) VALUES (?,?,?,?,?)`).run(tid,getKineticProviderAdapter().name,result.ok?1:0,result.latencyMs,result.message);res.json({...result,provider:getKineticProviderAdapter().name});});
  app.get("/api/kinetic-scanner/provider-health",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;res.json({items:rawDb.prepare(`SELECT provider_name AS provider,ok,latency_ms AS latencyMs,status_code AS statusCode,message,checked_at AS checkedAt FROM kinetic_provider_health WHERE tenant_id=? ORDER BY checked_at DESC LIMIT 100`).all(tid)});});
  app.get("/api/kinetic-scanner/state",read,(req,res)=>{const tid=requireTenant(req,res);if(tid){const state=scannerState(tid),memory=process.memoryUsage(),worker=state.scanWorker;const elapsed=worker?.startedAt?Math.max(1,(Date.now()-new Date(worker.startedAt).getTime())/1000):1;res.json({...state,recheckChecked:Number(state.recheckWorker?.checked??0),checksPerSecond:Number(((worker?.checked??0)/elapsed).toFixed(2)),memory:{heapUsedMb:Math.round(memory.heapUsed/1048576),rssMb:Math.round(memory.rss/1048576)}});}});
  app.get("/api/kinetic-scanner/worker-status",read,(req,res)=>{const tid=requireTenant(req,res);if(tid){const s=scannerState(tid);res.json({scanWorker:s.scanWorker,recheckWorker:s.recheckWorker});}});
  app.get("/api/kinetic-scanner/stats",read,(req,res)=>{const tid=requireTenant(req,res);if(tid)res.json(stats(tid));});
  app.get("/api/kinetic-scanner/states",read,(_req,res)=>res.json(KINETIC_STATES));
  app.post("/api/kinetic-scanner/search-addresses",manage,deps.requireScanningAllowed,deps.scanAdmission,async(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const parsed=kineticAddressSearchSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid Kinetic address search",issues:parsed.error.flatten()});try{const results=await getKineticProviderAdapter().searchAddresses(parsed.data),items=results.map(result=>({result,stored:upsertKineticAddress(tid,null,result)}));storage.logActivity(actor(req),"kinetic.address_search.completed","kinetic_scanner",undefined,{query:{city:parsed.data.city,state:parsed.data.state,zip:parsed.data.zip??null},results:items.length},req.ip);res.json({items:items.map(({result,stored})=>({id:stored.id,kineticAddressId:result.kineticAddressId,sequentialId:result.sequentialId,address:result.address,city:result.city,state:result.state,zip:result.zip,latitude:result.latitude,longitude:result.longitude,discoveryState:stored.discoveryState})),count:items.length});}catch(error){res.status(502).json({error:error instanceof Error?error.message:String(error)});}});

  app.post("/api/kinetic-scanner/start-scan",manage,deps.requireScanningAllowed,deps.scanAdmission,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const parsed=rangeSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid Sequential ID range",issues:parsed.error.flatten()});try{const jobId=startKineticScan({tenantId:tid,...parsed.data,createdBy:actor(req)});storage.logActivity(actor(req),"kinetic.scan.started","kinetic_scan_job",undefined,{jobId,...parsed.data},req.ip);res.status(202).json({jobId});}catch(error){res.status(409).json({error:error instanceof Error?error.message:String(error)});}});
  app.post("/api/kinetic-scanner/stop-scan",manage,(req,res)=>{const tid=requireTenant(req,res);if(tid)res.json({ok:stopKineticWorker(tid,"scan")});});
  app.post("/api/kinetic-scanner/pause-scan",manage,(req,res)=>{const tid=requireTenant(req,res);if(tid)res.json({ok:pauseKineticScan(tid)});});
  app.post("/api/kinetic-scanner/resume-scan",manage,(req,res)=>{const tid=requireTenant(req,res);if(tid)res.json({ok:resumeKineticScan(tid)});});
  app.post("/api/kinetic-scanner/start-recheck",manage,deps.requireScanningAllowed,deps.scanAdmission,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;try{const jobId=startKineticRecheck({tenantId:tid,createdBy:actor(req)});storage.logActivity(actor(req),"kinetic.recheck.started","kinetic_scan_job",undefined,{jobId},req.ip);res.status(202).json({jobId});}catch(error){res.status(409).json({error:error instanceof Error?error.message:String(error)});}});
  app.post("/api/kinetic-scanner/stop-recheck",manage,(req,res)=>{const tid=requireTenant(req,res);if(tid)res.json({ok:stopKineticWorker(tid,"recheck")});});

  app.get("/api/kinetic-scanner/addresses",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const parsed=listSchema.safeParse(req.query);if(!parsed.success)return res.status(400).json({error:"Invalid filters",issues:parsed.error.flatten()});const q=parsed.data,where=["a.tenant_id=?"],args:unknown[]=[tid];if(q.search){where.push("(lower(COALESCE(a.address,'')) LIKE lower(?) OR lower(COALESCE(a.city,'')) LIKE lower(?) OR a.zip LIKE ? OR lower(COALESCE(a.kinetic_address_id,'')) LIKE lower(?) OR CAST(a.sequential_id AS TEXT) LIKE ?)");const term=`%${q.search}%`;args.push(term,term,term,term,term);}if(q.state){where.push("a.state=?");args.push(q.state);}if(q.discoveryState){where.push("s.discovery_state=?");args.push(q.discoveryState);}if(q.liveOnly==="true")where.push("a.is_live=1");if(q.comingSoonOnly==="true")where.push("a.is_coming_soon=1");if(q.copperUpgradeCandidateOnly==="true")where.push("a.is_copper_upgrade_candidate=1");const clause=where.join(" AND "),from="kinetic_addresses a LEFT JOIN kinetic_address_state s ON s.address_id=a.id",total=Number((rawDb.prepare(`SELECT COUNT(*) count FROM ${from} WHERE ${clause}`).get(...args)as any)?.count??0),offset=(q.page-1)*q.limit;const items=rawDb.prepare(`SELECT a.id,kinetic_address_id AS kineticAddressId,sequential_id AS sequentialId,address,city,state,zip,latitude,longitude,exchange_id AS exchangeId,
    technology_type AS technologyType,maximum_qualification AS maximumQualification,estimated_completion_date AS estimatedCompletionDate,is_live AS isLive,is_coming_soon AS isComingSoon,
    is_copper_upgrade_candidate AS isCopperUpgradeCandidate,lead_id AS leadId,contact_enrichment_status AS contactEnrichmentStatus,last_checked_at AS lastChecked,last_status_change_at AS lastStatusChange,
    s.canonical_state AS canonicalState,s.discovery_state AS discoveryState,s.confirmation_count AS confirmationCount,s.verified_at AS verifiedAt
    FROM ${from} WHERE ${clause} ORDER BY a.last_checked_at DESC,a.id DESC LIMIT ? OFFSET ?`).all(...args,q.limit,offset);res.json({items,page:q.page,limit:q.limit,total,pages:Math.max(1,Math.ceil(total/q.limit))});});

  app.get("/api/kinetic-scanner/addresses/map",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const rows=rawDb.prepare(`SELECT a.id,a.latitude,a.longitude,a.is_live AS isLive,a.is_coming_soon AS isComingSoon,a.is_copper_upgrade_candidate AS isCopperUpgradeCandidate,a.address,a.city,a.state,s.discovery_state AS discoveryState FROM kinetic_addresses a LEFT JOIN kinetic_address_state s ON s.address_id=a.id WHERE a.tenant_id=? AND a.latitude IS NOT NULL AND a.longitude IS NOT NULL ORDER BY a.last_checked_at DESC LIMIT 10000`).all(tid)as any[];res.setHeader("Cache-Control","private, max-age=2, stale-while-revalidate=5");res.json({type:"FeatureCollection",features:rows.map(row=>({type:"Feature",id:row.id,geometry:{type:"Point",coordinates:[row.longitude,row.latitude]},properties:{id:row.id,address:row.address,city:row.city,state:row.state,isLive:row.isLive,isComingSoon:row.isComingSoon,isCopperUpgradeCandidate:row.isCopperUpgradeCandidate,discoveryState:row.discoveryState}}))});});
  app.get("/api/kinetic-scanner/map",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const rows=rawDb.prepare(`SELECT a.id,a.latitude,a.longitude,a.is_live AS isLive,a.is_coming_soon AS isComingSoon,a.is_copper_upgrade_candidate AS isCopperUpgradeCandidate,s.discovery_state AS discoveryState FROM kinetic_addresses a LEFT JOIN kinetic_address_state s ON s.address_id=a.id WHERE a.tenant_id=? AND a.latitude IS NOT NULL AND a.longitude IS NOT NULL LIMIT 10000`).all(tid)as any[];res.json({type:"FeatureCollection",features:rows.map(r=>({type:"Feature",id:r.id,geometry:{type:"Point",coordinates:[r.longitude,r.latitude]},properties:{id:r.id,isLive:r.isLive,isComingSoon:r.isComingSoon,isCopperUpgradeCandidate:r.isCopperUpgradeCandidate,discoveryState:r.discoveryState}}))});});
  app.get("/api/kinetic-scanner/addresses/:id",read,(req,res)=>{const tid=requireTenant(req,res),id=idSchema.safeParse(req.params.id);if(!tid)return;if(!id.success)return res.status(400).json({error:"Invalid address id"});const address=addressRow(tid,id.data);if(!address)return res.status(404).json({error:"Address not found"});const observations=(rawDb.prepare(`SELECT id,response_hash AS responseHash,raw_response_json AS rawResponse,observed_at AS observedAt FROM kinetic_address_observations WHERE tenant_id=? AND address_id=? ORDER BY observed_at DESC LIMIT 100`).all(tid,id.data)as any[]).map(row=>({...row,rawResponse:parseRaw(row.rawResponse)}));const changes=rawDb.prepare(`SELECT id,field_name AS fieldName,previous_value AS previousValue,current_value AS currentValue,observed_at AS observedAt FROM kinetic_address_changes WHERE tenant_id=? AND address_id=? ORDER BY observed_at DESC`).all(tid,id.data);const episodes=rawDb.prepare(`SELECT id,episode_sequence AS episodeSequence,status,detection_from AS detectionFrom,detection_to AS detectionTo,confirmation_count AS confirmationCount,model_version AS modelVersion,candidate_at AS candidateAt,verified_at AS verifiedAt,regressed_at AS regressedAt FROM kinetic_transition_episodes WHERE tenant_id=? AND address_id=? ORDER BY episode_sequence DESC`).all(tid,id.data);res.json({address,observations,changes,episodes});});
  app.get("/api/kinetic-scanner/addresses/:id/contacts",read,(req,res)=>{const tid=requireTenant(req,res),id=idSchema.safeParse(req.params.id);if(!tid)return;if(!id.success)return res.status(400).json({error:"Invalid address id"});const contacts=rawDb.prepare(`SELECT id,name,phone_last4 AS phoneLast4,provider,confidence,refreshed_at AS refreshedAt FROM kinetic_address_contacts WHERE tenant_id=? AND address_id=? ORDER BY refreshed_at DESC`).all(tid,id.data);res.json({contacts});});
  app.post("/api/kinetic-scanner/addresses/:id/contacts/refresh",manage,async(req,res)=>{const tid=requireTenant(req,res),id=idSchema.safeParse(req.params.id);if(!tid)return;if(!id.success)return res.status(400).json({error:"Invalid address id"});try{const leadId=convertAddress(tid,id.data);rawDb.prepare(`UPDATE kinetic_addresses SET contact_enrichment_status='running' WHERE tenant_id=? AND id=?`).run(tid,id.data);const result=await enrichCallingLead({tenantId:tid,leadId,actorUserId:actor(req)??0,idempotencyKey:`kinetic:${id.data}:${new Date().toISOString().slice(0,10)}`,correlationId:String((req as any).id??crypto.randomUUID())});rawDb.prepare(`UPDATE kinetic_addresses SET contact_enrichment_status='completed',updated_at=datetime('now') WHERE tenant_id=? AND id=?`).run(tid,id.data);res.json({ok:true,leadId,enrichmentId:result.enrichmentId,matchCount:result.matchCount});}catch(error){rawDb.prepare(`UPDATE kinetic_addresses SET contact_enrichment_status='failed' WHERE tenant_id=? AND id=?`).run(tid,id.success?id.data:-1);res.status(409).json({error:error instanceof Error?error.message:String(error)});}});
  app.post("/api/kinetic-scanner/addresses/:id/recheck",manage,(req,res)=>{const tid=requireTenant(req,res),id=idSchema.safeParse(req.params.id);if(!tid)return;if(!id.success)return res.status(400).json({error:"Invalid address id"});const row=addressRow(tid,id.data);if(!row?.kineticAddressId)return res.status(409).json({error:"Kinetic Address ID is required for recheck"});void getKineticProviderAdapter().lookup({kineticAddressId:row.kineticAddressId}).then(result=>{if(result)upsertKineticAddress(tid,null,result);}).catch(()=>undefined);res.status(202).json({queued:true});});
  app.post("/api/kinetic-scanner/addresses/:id/convert-lead",manage,(req,res)=>{const tid=requireTenant(req,res),id=idSchema.safeParse(req.params.id);if(!tid)return;if(!id.success)return res.status(400).json({error:"Invalid address id"});try{res.status(201).json({leadId:convertAddress(tid,id.data)});}catch(error){res.status(409).json({error:error instanceof Error?error.message:String(error)});}});

  app.get("/api/kinetic-scanner/changes",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const limit=Math.max(1,Math.min(500,Number(req.query.limit)||100));const items=rawDb.prepare(`SELECT c.id,c.address_id AS addressId,a.kinetic_address_id AS kineticAddressId,a.sequential_id AS sequentialId,a.address,a.city,a.state,c.field_name AS fieldName,c.previous_value AS previousValue,c.current_value AS currentValue,c.observed_at AS changedAt FROM kinetic_address_changes c JOIN kinetic_addresses a ON a.id=c.address_id WHERE c.tenant_id=? ORDER BY c.observed_at DESC LIMIT ?`).all(tid,limit);res.json({items});});
  app.get("/api/kinetic-scanner/changes/stats",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;res.json(rawDb.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN observed_at>=datetime('now','-24 hours') THEN 1 ELSE 0 END) last24Hours FROM kinetic_address_changes WHERE tenant_id=?`).get(tid));});
  app.get("/api/kinetic-scanner/transitions",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const items=rawDb.prepare(`SELECT e.id,e.address_id AS addressId,e.episode_sequence AS episodeSequence,e.status,e.detection_from AS detectionFrom,e.detection_to AS detectionTo,e.confirmation_count AS confirmationCount,e.model_version AS modelVersion,e.candidate_at AS candidateAt,e.verified_at AS verifiedAt,e.regressed_at AS regressedAt,a.address,a.city,a.state,a.zip,a.latitude,a.longitude FROM kinetic_transition_episodes e JOIN kinetic_addresses a ON a.id=e.address_id AND a.tenant_id=e.tenant_id WHERE e.tenant_id=? ORDER BY e.candidate_at DESC LIMIT 500`).all(tid);res.json({items,claim:"First observed by HomeFront; provider change time is interval-censored."});});
  app.get("/api/kinetic-scanner/jobs/:id/items",read,(req,res)=>{const tid=requireTenant(req,res),jobId=z.string().uuid().safeParse(req.params.id);if(!tid)return;if(!jobId.success)return res.status(400).json({error:"Invalid job id"});const items=rawDb.prepare(`SELECT id,item_key AS itemKey,sequential_id AS sequentialId,kinetic_address_id AS kineticAddressId,priority,status,attempts,available_at AS availableAt,lease_owner AS leaseOwner,lease_expires_at AS leaseExpiresAt,last_error AS lastError,completed_at AS completedAt FROM kinetic_scan_job_items WHERE tenant_id=? AND job_id=? ORDER BY id DESC LIMIT 500`).all(tid,jobId.data);res.json({items});});
  app.get("/api/kinetic-scanner/hotspots",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const hotspots=rawDb.prepare(`SELECT city,state,zip,COUNT(*) addressCount,SUM(CASE WHEN is_live=1 THEN 1 ELSE 0 END) liveCount,SUM(CASE WHEN is_copper_upgrade_candidate=1 THEN 1 ELSE 0 END) copperUpgradeCount,AVG(latitude) latitude,AVG(longitude) longitude,MAX(last_checked_at) lastChecked FROM kinetic_addresses WHERE tenant_id=? GROUP BY city,state,zip HAVING COUNT(*)>=2 ORDER BY liveCount DESC,addressCount DESC LIMIT 250`).all(tid);res.json({hotspots});});
  app.get("/api/kinetic-scanner/live-clusters",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const clusters=rawDb.prepare(`SELECT city,state,zip,COUNT(*) addressCount,AVG(latitude) latitude,AVG(longitude) longitude FROM kinetic_addresses WHERE tenant_id=? AND is_live=1 GROUP BY city,state,zip HAVING COUNT(*)>=2 ORDER BY addressCount DESC LIMIT 250`).all(tid);res.json({clusters});});
  app.get("/api/kinetic-scanner/export",read,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const rows=rawDb.prepare(`SELECT kinetic_address_id AS kineticAddressId,sequential_id AS sequentialId,address,city,state,zip,latitude,longitude,exchange_id AS exchangeId,technology_type AS technologyType,maximum_qualification AS maximumQualification,estimated_completion_date AS estimatedCompletionDate,is_live AS isLive,is_coming_soon AS isComingSoon,is_copper_upgrade_candidate AS isCopperUpgradeCandidate,last_checked_at AS lastChecked FROM kinetic_addresses WHERE tenant_id=? ORDER BY sequential_id`).all(tid)as any[];const headers=["kineticAddressId","sequentialId","address","city","state","zip","latitude","longitude","exchangeId","technologyType","maximumQualification","estimatedCompletionDate","isLive","isComingSoon","isCopperUpgradeCandidate","lastChecked"];res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",`attachment; filename="kinetic-addresses-${new Date().toISOString().slice(0,10)}.csv"`);res.send([headers.join(","),...rows.map(row=>headers.map(key=>csvCell(row[key])).join(","))].join("\n"));});
  app.post("/api/kinetic-scanner/backfill-copper-upgrade",manage,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;const observations=rawDb.prepare(`SELECT raw_response_json raw FROM kinetic_address_observations WHERE tenant_id=? ORDER BY observed_at DESC`).all(tid)as any[];let candidates=0,updated=0;for(const observation of observations){const normalized=normalizeConfiguredKineticResponse(parseRaw(observation.raw));if(normalized.isCopperUpgradeCandidate===true){candidates++;const result=upsertKineticAddress(tid,null,normalized);if(result.changed)updated++;}}res.json({candidates,updated});});
  app.delete("/api/kinetic-scanner/clear",manage,(req,res)=>{const tid=requireTenant(req,res);if(!tid)return;if(req.body?.confirm!=="CLEAR KINETIC DATA")return res.status(400).json({error:'Confirmation must equal "CLEAR KINETIC DATA"'});clearKineticData(tid);storage.logActivity(actor(req),"kinetic.data.cleared","kinetic_scanner",undefined,{},req.ip);res.json({ok:true});});
}

function convertAddress(tenantId:number,addressId:number):number{
  const row=addressRow(tenantId,addressId);if(!row)throw new Error("Address not found");if(row.leadId)return Number(row.leadId);if(!row.address||!row.city||!row.state||!row.zip)throw new Error("A complete postal address is required before lead conversion");
  const existing=rawDb.prepare(`SELECT id FROM leads WHERE tenant_id=? AND lower(address)=lower(?) AND lower(city)=lower(?) AND state=? AND zip=? LIMIT 1`).get(tenantId,row.address,row.city,row.state,row.zip)as any;
  const leadId=existing?.id??storage.createLead({tenantId,address:row.address,city:row.city,state:row.state,zip:row.zip,lat:row.latitude,lng:row.longitude,fiberStatus:row.isLive?"live":row.isComingSoon?"coming_soon":"unknown",techType:row.technologyType,maxDownloadMbps:row.maximumQualification==null?null:Math.round(row.maximumQualification),exchangeId:row.exchangeId,leadStatus:"prospect"}as any).id;
  rawDb.prepare(`UPDATE kinetic_addresses SET lead_id=?,updated_at=datetime('now') WHERE tenant_id=? AND id=?`).run(leadId,tenantId,addressId);return Number(leadId);
}
