import { useEffect,useRef,useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle,Loader2,MapPin } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { kineticScannerApi } from "@/lib/kineticScannerApi";
declare const mapboxgl:any;
export function KineticScannerMap({onOpen}:{onOpen:(id:number)=>void}){
  const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null);const[token,setToken]=useState<string|null>(null),[failed,setFailed]=useState(false);
  const{data,isLoading,error}=useQuery({queryKey:["kinetic-scanner-map"],queryFn:kineticScannerApi.map,staleTime:15_000});
  useEffect(()=>{apiRequest("GET","/api/config/map").then(r=>r.json()).then(d=>{if(d?.token){mapboxgl.accessToken=d.token;setToken(d.token)}else setFailed(true)}).catch(()=>setFailed(true));},[]);
  useEffect(()=>{if(!token||!host.current||!data||mapRef.current)return;const first=data.features?.[0]?.geometry?.coordinates,map=new mapboxgl.Map({container:host.current,style:"mapbox://styles/mapbox/dark-v11",center:first??[-80.25,35.82],zoom:first?9:5,attributionControl:false});mapRef.current=map;map.addControl(new mapboxgl.NavigationControl({showCompass:false}),"top-right");map.on("load",()=>{map.addSource("kinetic-addresses",{type:"geojson",data,cluster:true,clusterRadius:50,clusterMaxZoom:13});map.addLayer({id:"kinetic-clusters",type:"circle",source:"kinetic-addresses",filter:["has","point_count"],paint:{"circle-color":["step",["get","point_count"],"#00A94F",50,"#F59E0B",250,"#8B5CF6"],"circle-radius":["step",["get","point_count"],18,50,24,250,31],"circle-stroke-width":2,"circle-stroke-color":"#071A11"}});map.addLayer({id:"kinetic-count",type:"symbol",source:"kinetic-addresses",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":12},paint:{"text-color":"#fff"}});map.addLayer({id:"kinetic-points",type:"circle",source:"kinetic-addresses",filter:["!",["has","point_count"]],paint:{"circle-radius":7,"circle-color":["case",["==",["get","isLive"],1],"#00A94F",["==",["get","isComingSoon"],1],"#8B5CF6",["==",["get","isCopperUpgradeCandidate"],1],"#F59E0B","#64748B"],"circle-stroke-width":2,"circle-stroke-color":"#ECFDF5"}});map.on("click","kinetic-clusters",(event:any)=>{const f=map.queryRenderedFeatures(event.point,{layers:["kinetic-clusters"]})[0];map.getSource("kinetic-addresses").getClusterExpansionZoom(f.properties.cluster_id,(err:any,zoom:number)=>{if(!err)map.easeTo({center:f.geometry.coordinates,zoom})})});map.on("click","kinetic-points",(event:any)=>{const id=Number(event.features?.[0]?.properties?.id);if(Number.isInteger(id))onOpen(id)});});return()=>{map.remove();mapRef.current=null};},[token,data,onOpen]);
  if(isLoading)return <div className="grid h-[520px] place-items-center rounded-2xl border border-emerald-900/50 bg-[#071A11]"><Loader2 className="h-5 w-5 animate-spin text-[#00A94F]"/></div>;
  if(error||failed)return <div className="grid h-[520px] place-items-center rounded-2xl border border-border bg-card text-sm text-muted-foreground"><AlertTriangle className="mr-2 inline h-5 w-5 text-red-500"/>Map unavailable</div>;
  if(!data?.features?.length)return <div className="grid h-[520px] place-items-center rounded-2xl border border-dashed border-border bg-card text-sm text-muted-foreground"><MapPin className="mr-2 inline h-5 w-5"/>No geocoded Kinetic addresses yet</div>;
  return <div className="overflow-hidden rounded-2xl border border-emerald-900/50"><div ref={host} className="h-[520px] w-full"/></div>;
}
