import { useEffect,useRef,useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle,Loader2,MapPin } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { kineticScannerApi } from "@/lib/kineticScannerApi";
export function KineticScannerMap({onOpen}:{onOpen:(id:number)=>void}){
  const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),onOpenRef=useRef(onOpen),hasFitRef=useRef(false);const[token,setToken]=useState<string|null>(null),[failed,setFailed]=useState(false);
  const{data,isLoading,error}=useQuery({queryKey:["kinetic-scanner-map"],queryFn:kineticScannerApi.map,staleTime:2_000,refetchInterval:3_000,refetchIntervalInBackground:false});
  useEffect(()=>{onOpenRef.current=onOpen},[onOpen]);
  useEffect(()=>{let cancelled=false;const init=()=>{apiRequest("GET","/api/config/map").then(r=>r.json()).then(d=>{if(cancelled)return;if(d?.token&&(window as any).mapboxgl){(window as any).mapboxgl.accessToken=d.token;setToken(d.token)}else setFailed(true)}).catch(()=>{if(!cancelled)setFailed(true)})};(window as any).__onMapboxReady(init);return()=>{cancelled=true}},[]);
  useEffect(()=>{const mb=(window as any).mapboxgl;if(!token||!mb||!host.current||mapRef.current)return;const map=new mb.Map({container:host.current,style:"mapbox://styles/mapbox/dark-v11",center:[-80.25,35.82],zoom:5,attributionControl:false});mapRef.current=map;map.addControl(new mb.NavigationControl({showCompass:false}),"top-right");map.on("load",()=>{map.addSource("kinetic-addresses",{type:"geojson",data:{type:"FeatureCollection",features:[]},cluster:true,clusterRadius:50,clusterMaxZoom:13});map.addLayer({id:"kinetic-clusters",type:"circle",source:"kinetic-addresses",filter:["has","point_count"],paint:{"circle-color":["step",["get","point_count"],"#00A94F",50,"#F59E0B",250,"#8B5CF6"],"circle-radius":["step",["get","point_count"],18,50,24,250,31],"circle-stroke-width":2,"circle-stroke-color":"#071A11"}});map.addLayer({id:"kinetic-count",type:"symbol",source:"kinetic-addresses",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":12},paint:{"text-color":"#fff"}});map.addLayer({id:"kinetic-points",type:"circle",source:"kinetic-addresses",filter:["!",["has","point_count"]],paint:{"circle-radius":["case",["==",["get","discoveryState"],"VERIFIED_FRESH"],9,7],"circle-color":["case",["==",["get","discoveryState"],"VERIFIED_FRESH"],"#22C55E",["==",["get","discoveryState"],"CANDIDATE_FRESH"],"#A855F7",["==",["get","discoveryState"],"BASELINE_FIBER"],"#38BDF8",["==",["get","isLive"],1],"#00A94F",["==",["get","isComingSoon"],1],"#8B5CF6",["==",["get","isCopperUpgradeCandidate"],1],"#F59E0B","#64748B"],"circle-stroke-width":2,"circle-stroke-color":"#ECFDF5"}});map.on("click","kinetic-clusters",(event:any)=>{const f=map.queryRenderedFeatures(event.point,{layers:["kinetic-clusters"]})[0],source=map.getSource("kinetic-addresses");if(!f||!source)return;source.getClusterExpansionZoom(f.properties.cluster_id,(err:any,zoom:number)=>{if(!err)map.easeTo({center:f.geometry.coordinates,zoom,duration:450})})});map.on("click","kinetic-points",(event:any)=>{const id=Number(event.features?.[0]?.properties?.id);if(Number.isInteger(id))onOpenRef.current(id)});for(const layer of ["kinetic-clusters","kinetic-points"]){map.on("mouseenter",layer,()=>{map.getCanvas().style.cursor="pointer"});map.on("mouseleave",layer,()=>{map.getCanvas().style.cursor=""})}});return()=>{map.remove();mapRef.current=null;hasFitRef.current=false};},[token]);
  useEffect(()=>{const map=mapRef.current,mb=(window as any).mapboxgl;if(!map||!mb||!data)return;const apply=()=>{const source=map.getSource("kinetic-addresses");if(!source)return;source.setData(data);if(hasFitRef.current||!data.features?.length)return;const bounds=new mb.LngLatBounds();for(const feature of data.features){const coordinates=feature?.geometry?.coordinates;if(Array.isArray(coordinates)&&coordinates.length===2)bounds.extend(coordinates)}if(!bounds.isEmpty()){hasFitRef.current=true;map.fitBounds(bounds,{padding:48,maxZoom:13,duration:650})}};if(map.isStyleLoaded())apply();else map.once("load",apply);},[data]);
  if(error||failed)return <div className="grid h-[520px] place-items-center rounded-2xl border border-border bg-card text-sm text-muted-foreground"><AlertTriangle className="mr-2 inline h-5 w-5 text-red-500"/>Map unavailable</div>;
  return <div className="relative overflow-hidden rounded-2xl border border-emerald-900/50"><div ref={host} className="h-[min(68vh,720px)] min-h-[520px] w-full"/>{isLoading&&<div className="pointer-events-none absolute left-3 top-3 flex items-center gap-2 rounded-full bg-[#071A11]/90 px-3 py-2 text-[10px] font-semibold text-emerald-100"><Loader2 className="h-3.5 w-3.5 animate-spin text-[#00A94F]"/>Loading Kinetic addresses</div>}{!isLoading&&!data?.features?.length&&<div className="pointer-events-none absolute inset-x-4 bottom-4 flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-[#071A11]/90 p-3 text-xs text-emerald-100/70"><MapPin className="h-4 w-4"/>Pins appear here automatically as geocoded scan results arrive.</div>}</div>;
}
